# 开发环境下使用，支持热更新，重启生效
isWatch: false
# 是否在控制台输出UC插件调试日志。开发者模式下，会强制开启调试日志
log: true
# 是否在控制台输出UC插件普通日志
debugLog: false
# 是否合并插件主人和机器人主人
isDefaultMaster: true
# 是否仅主人可使用UC插件所有功能，开启后除主人的所有人UC功能皆不响应
onlyMaster: false
# 是否强制使所有设置仅以全局为准，开启后所有设置仅以全局为准，不再区分群聊全局，插件权限仅保留全局即-2 0 2 4，指定群的设置将处于冻结状态，不可修改也不会生效，若不需要每个群自定义可开启
# onlyGlobal: false
# UC插件优先级，优先级越小越优先响应，可为任意整数，重启生效
priority: 251
# 插件api服务的服务器，建议1，如遇api网络问题可以尝试切换（1已经寄了，悲）
server: 2
# UC插件的机器人名称，用于个别时候的机器人回复或开关Bot的指令等
BotName: 纳西妲
# 允许响应前缀，不是“仅前缀”而是使BotName+指令也能正常触发，用于避免在多机器人的群内只想要操作某一机器人时“一呼百应”
globalPrefix: false
# 每日零点loveMys剩余过码次数小于等于该值时自动提醒主人，0则不提醒
loveMysNotice: 50
# 用户无权限进行某操作时，机器人的回复
noPerReply: 无权限
# 机器人无权限进行某操作时，机器人的回复
noPowReply: 主淫，小的权限不足，无法执行该操作嘤嘤嘤~
# api服务连接失败时机器人的回复
fetchErrReply: API连接失败，请稍后或切换服务后重试
# 帮助图折叠显示部分，不折叠则直接在#UC帮助 中显示该模块完整帮助
helpFold:
  - 系统
  - 群管
  - 签名
  - 排队
  - 戳一戳
  - 随机老婆
  - 水群统计
  - 戳主人
  - 艾特主人
  - loveMys

# qsign重启设置
qsignRestart:
  # 启动Bot后是否自动开启签名重启检测，开启此项后重启生效
  isAutoOpen: false
  # 是否每日自动清理签名生成的日志文件
  isAutoClearLog: false
  # 隐藏重启的签名的窗口。注意：开启此项后，关闭机器人将同时关闭签名。不建议开启
  windowsHide: false
  # 签名崩溃检测
  switch1: true
  # 签名异常检测
  switch2: true
  # 签名异常次数大于等于该值时执行签名重启
  errorTimes: 3
  # 签名启动器执行路径，不填则取默认路径
  qsign: null
  # 签名host
  host: 127.0.0.1
  # 签名port
  port: 801
  # 签名启动器名称
  qsingRunner: 一键startAPI.bat
  # 崩溃检测时间间隔，单位秒，不建议低于10
  sleep: 60

# 单独上下班设置
switchBot:
  # Bot上班的指令：插件中设置的BotName+下面的关键词即可触发，多个请用|间隔
  openReg: 上班|工作
  # Bot下班的指令：插件中设置的BotName+下面的关键词即可触发，多个请用|间隔
  closeReg: 下班|休息
  # 开启Bot的回复，BotName会被替换为上面设置的BotName的值
  openMsg: 好哒，BotName开始上班啦！
  # 关闭Bot的回复，BotName会被替换为上面设置的BotName的值
  closeMsg: BotName休息去啦~
  # 使用权限
  use:
    # 是否仅主人可使用
    isM: false
    # 是否允许群插件管理员使用，关闭仅主人或群原生管理员可使用
    isA: true
    # 是否允许群原生管理员使用，关闭仅主人或插件群管理员可使用
    isGA: false
    # 是否允许任何人
    isE: false
  # 在关闭群聊的情况下，以BotName开头的消息是否也响应
  isPrefix: true
  # 在关闭群聊的情况下，艾特机器人的消息是否也响应
  isAt: true
  # 在关闭群聊且开启了上述两项(之一)的情况下，响应指令的权限配置
  closedCommand:
    # 是否仅主人
    isM: false
    # 是否允许群插件管理员
    isA: true
    # 是否允许群原生管理员
    isGA: false
    # 是否允许任何人
    isE: false

# JS插件管理系统
JSsystem:
  # 是否启用UC插件JS插件管理系统
  isOpen: true
  # 一次性查看多个JS文件时是否自动压缩为zip发送
  isZip: false
  # 群聊发送文件后自动撤回时长，0-120秒，0为不撤回
  recallFileGroup: 0
  # 私聊发送文件后自动撤回时长，4-120秒，0为不撤回
  recallFilePrivate: 0

# 备份、还原数据设置
BackupRestore:
  # 是否自动备份云崽、example、插件数据和JS等，开启前请尝试#UC备份数据 是否可用
  autoBackup: false
  # 自动备份执行的cron，默认为每天23点59分执行，修改后重启生效
  cron: 0 59 23 * * ?
  # 备份文件保存天数，超过此天数的以前的备份数据将会被清理，减少磁盘占用，0为不限制
  retentionDays: 0
  # 要备份的各个插件根目录下的文件夹，数据主要保存于data和config，可自行添加文件夹
  Directory:
    - config
    - data
  # 要排除的备份文件夹，递归复制时如果遇见此类文件夹会跳过
  removeDirectory:
    - .git
    - node_modules
  # 除上述包括的、需要额外备份的指定文件或文件夹，若为文件则备份文件，若为文件夹则递归备份文件夹，必须使用相对于崽根目录的路径，比如./logs
  extra: []

# 戳一戳设置
chuoyichuo:
  # 是否开启UC戳一戳
  isOpen: false
  # 被戳是否自动更新群名片
  isAutoSetCard: true
  # 开启被戳自动更新群名片后，群名片后缀内容，num会被替换为被戳次数
  groupCard: 今日已被戳num次~
  # 戳一戳使用的图包的名称（自动群名片会取此图包名称）
  picPath: 纳西妲
  # 戳一戳CD，0为不限制，各群独立，单位秒
  CD: 0
  # 被戳回复文本+图片概率
  textimg: 0.8
  # 当回复文字(汉字数>=3)时，将文字转语音的概率，speaker取图包名称，可选角色见#UC音色列表，此概率独立于整体概率，可选0-0.5
  AiRecord: 0.1
  # 被戳回复被戳次数+文本+图片概率，此概率独立于整体概率，意为触发文本+图片回复时又有多少概率在文本前加上被戳次数，可选0-1
  chuoimg: 0.2
  # 被戳回复头像表情包概率
  face: 0.1
  # 被戳禁言对方概率，剩下的就是反击概率
  mute: 0.05
  # 禁言的时长，单位分，0为不禁言
  muteTime: 2

# 戳主人回复设置
chuoMaster:
  # 是否开启UC戳主人回复
  isOpen: false
  # 回复时是否同时艾特对方
  isAt: false
  # 戳主人回复消息概率，0-1
  text: 0.6
  # 戳主人发送合成表情包概率，0-1
  img: 0.1
  # 戳主人反击概率，0-1
  poke: 0.2
  # 戳主人禁言概率，0-1
  mute: 0.1
  # 禁言的时长，单位分，0为不禁言
  muteTime: 2

# 艾特主人回复设置
atMaster:
  # 是否开启UC艾特主人回复
  isOpen: false
  # 艾特主人回复的概率，0-1
  probability: 0.5
  # 回复时是否同时艾特对方
  isAt: false
  # 满足此权限条件的用户才可能会触发艾特主人回复
  use:
    # 是否仅主人可使用
    isM: false
    # 是否允许群插件管理员使用
    isA: true
    # 是否允许群原生管理员使用
    isGA: true
    # 是否允许任何人使用
    isE: true

# 随机老婆设置
randomWife:
  # 是否开启UC随机老婆
  isOpen: true
  # 每日取老婆次数限制，包括主人
  wifeLimits: 1
  # 娶老婆达到次数限制后机器人的回复
  limitedReply: 不要贪心哦！
  # 增加随机老婆权限
  add:
    # 是否仅主人可使用#上传随机老婆
    isM: false
    # 是否允许群插件管理员使用#上传随机老婆
    isA: true
    # 是否允许群原生管理员使用#上传随机老婆
    isGA: true
    # 是否允许任何人使用#上传随机老婆
    isE: false
  # 删除随机老婆权限
  del:
    # 是否仅主人可使用#删除随机老婆
    isM: false
    # 是否允许群插件管理员使用#删除随机老婆
    isA: true
    # 是否允许群原生管理员使用#删除随机老婆
    isGA: false
    # 是否允许任何人使用#删除随机老婆
    isE: false

# 随机群友设置
randomMember:
  # 是否开启UC随机群友
  isOpen: true
  # 是否自动艾特随机到的群友
  isAt: false
  # 触发指令，#你设置的值 就可以触发该插件，修改后直接生效，英语字母大小写都可以触发，仅以全局为准
  keyWords: 随机群友
  # 随机群友回复内容，info会被替换为群友信息：群友昵称（QQ）
  reply: 恭喜info成为天选之子！
  # 使用权限
  use:
    # 是否仅主人可使用
    isM: false
    # 是否允许群插件管理员使用
    isA: true
    # 是否允许群原生管理员使用
    isGA: true
    # 是否允许任何人使用
    isE: true

# 伪装群友设置
camouflage:
  # 是否开启UC伪装群友功能
  isOpen: true
  # 单次伪装时长，单位分钟
  time: 10
  # 单次伪装结束后CD，单位分钟
  CD: 10
  # 每群每人每天伪装次数限制，0为不限制，最多不超过10
  timesLimit: 3
  # 消息数量限制，单次伪装发送的消息数量超过此值会直接退出伪装，0为不限制
  msgLimit: 251
  # 伪装期间是否不响应指令（#结束伪装 除外）
  isSilent: false
  # 使用、结束权限
  use:
    # 是否仅主人可使用
    isM: false
    # 是否允许群插件管理员使用
    isA: true
    # 是否允许群原生管理员使用
    isGA: true
    # 是否允许任何人使用
    isE: true

# B站直播推送设置
BlivePush:
  # 群聊推送全局开关
  isGroup: true
  # 私聊推送全局开关
  isPrivate: true
  # 推送检测间隔，单位分钟，不建议小于4，仅以全局为准，重启生效
  mins: 4
  # 订阅权限
  use:
    # 是否允许群聊使用，关闭仅主人可群聊使用
    isG: true
    # 是否允许私聊使用，关闭仅主人可私聊使用
    isP: false
    # 是否仅主人可使用
    isM: false
    # 是否允许群插件管理员使用
    isA: true
    # 是否允许群原生管理员使用
    isGA: true
    # 是否允许任何人使用
    isE: false

# 放大图片设置
bigjpg:
  # 是否开启UC放大图片
  isOpen: true
  # 放大图片key
  apiKey:
  # 放大风格，art和photo，代表卡通和照片，卡通图片放大效果最佳
  style: art
  # 每人每天放大次数限制，0为不限制，主人不受限
  limits: 3
  # 放大的图片是否自动保存，保存位置 resources/bigjpg
  isSave: false
  # 4倍，关闭仅允许主人放大4倍
  x4: true
  # 8倍，关闭仅允许主人放大8倍
  x8: true
  # 16倍，关闭仅允许主人放大16倍
  x16: true
  # 订阅权限
  use:
    # 是否允许群聊使用
    isG: true
    # 是否允许私聊使用
    isP: false
    # 是否仅主人可使用
    isM: false
    # 是否允许群插件管理员使用
    isA: true
    # 是否允许群原生管理员使用
    isGA: true
    # 是否允许任何人使用
    isE: false

# 水群统计设置
sqtj:
  # 是否开启UC水群统计
  isOpen: true
  # 水群统计是否也统计机器人自身记录
  isSelf: false
  # 每日0点是否自动发送水群统计至群内，建议在需要打开的群内单独开启，否则可能每个群都会发送
  isAutoSend: false
  # 水群统计排名人数
  rankNum: 10
  # 使用权限
  use:
    # 是否仅主人可使用
    isM: false
    # 是否允许群插件管理员使用
    isA: true
    # 是否允许群原生管理员使用
    isGA: true
    # 是否允许任何人使用
    isE: true

# 活动截止提醒设置
ActReminder:
  # 原神活动截止提醒开关，建议只在需要的群内单独开启
  opIsOpen: false
  # 星铁活动截止提醒开关，建议只在需要的群内单独开启
  srIsOpen: false
  # 原神活动检测时间cron表达式，仅以全局设置为准，默认为每天12点检测，修改后重启生效
  opCron: 0 0 12 * * ?
  # 星铁活动检测时间cron表达式，仅以全局设置为准，默认为每天12点检测，修改后重启生效
  srCron: 0 0 12 * * ?
  # 每次检测时若原神活动剩余天数小于等于该值则提醒（忽略时分秒）
  opDays: 1
  # 每次检测时若星铁活动剩余天数小于等于该值则提醒（忽略时分秒）
  srDays: 1
  # 原神活动截止提醒是否艾特全员（需管理员权限）
  opAtAll: false
  # 星铁活动截止提醒是否艾特全员（需管理员权限）
  srAtAll: false

# 复读打断设置
RepeatInterruption:
  # 复读开关，复读、打断二选一，若同时开启，则只复读不打断
  Repeat: false
  # 打断开关，复读、打断二选一，若同时开启，则只复读不打断
  Interruption: false
  # 同一消息连续且重复次数达到该值时触发复读或打断
  times: 3
  # 打断消息，选择打断时发送的打断消息，支持图链或文件绝对地址
  interruptionMsg:
  # 乱序打断开关，选择打断时是否将该消息的乱序作为打断消息，开启后忽略上一项设置（仅限文本，图片时取上一项设置的打断消息）
  mix: true
