# 用于开发环境的功能，可热更新app，如果有需要可以开启
isWatch: false
# 是否输出UC插件日志。开发者模式下，会强制开启调试日志
log: true
# 是否输出UC插件debug日志
debugLog: false
# 插件主人是否和机器人主人合并，不影响插件管理员设置
isDefaultMaster: true
# 是否仅主人可操作UC插件
onlyMaster: false
# UC插件优先级，优先级越小越优先响应，可为任意整数
priority: 251
# 插件api服务的服务器，建议1，如遇api网络问题可以尝试切换
server: 1
# UC插件的机器人自称，用于个别时候的机器人回复或开关Bot的指令等
BotName: 纳西妲
# 每日零点loveMys剩余过码次数小于等于该值时自动提醒主人，0则不提醒
loveMysNotice: 50
# 仅主人可操作时，对本拥有权限的管理员的回复
onlyMasterReply: 当前仅允许主人操作
# 用户无权限进行某操作时，机器人的回复
noPerReply: 无权限
# 机器人无权限进行某操作时，机器人的回复
noPowReply: 主淫，小的权限不足，无法执行该操作嘤嘤嘤~
# api服务连接失败时机器人的回复
fetchErrReply: 服务连接失败，请稍后重试

# qsign重启设置
qsignRestart:
  # 启动Bot后是否自动开启签名重启检测，开启此项后重启生效
  isAutoOpen: false
  # 签名崩溃检测
  switch1: true
  # 签名异常检测
  switch2: true
  # 签名异常次数大于等于该值时执行签名重启
  errorTimes: 3
  # 签名启动器执行路径，不填则取默认路径
  qsign: null
  # 签名host
  host: 127.0.0.1
  # 签名port
  port: 801
  # 签名启动器名称
  qsingRunner: 一键startAPI.bat
  # 崩溃检测时间间隔，单位秒，不建议低于10
  sleep: 60

# 单独上下班设置
switchBot:
  # 开启Bot的回复，BotName会被替换为上面设置的BotName的值
  openMsg: 好哒，BotName开始上班啦！
  # 关闭Bot的回复，BotName会被替换为上面设置的BotName的值
  closeMsg: BotName休息去啦~
  # Bot上班的指令：插件中设置的BotName+下面的关键词即可触发，多个请用|间隔
  openReg: 上班|工作
  # Bot下班的指令：插件中设置的BotName+下面的关键词即可触发，多个请用|间隔
  closeReg: 下班|休息
  # 使用权限
  use:
    # 是否仅主人可使用
    isM: false
    # 是否允许群插件管理员使用，关闭仅主人或群原生管理员可使用
    isA: true
    # 是否允许群原生管理员使用，关闭仅主人或插件群管理员可使用
    isGA: false
  # 在关闭群聊的情况下，以BotName开头的消息是否也响应
  isPrefix: true
  # 在关闭群聊的情况下，艾特机器人的消息是否也响应
  isAt: true
  # 在关闭群聊且开启了上述两项(之一)的情况下，响应指令的权限配置
  closedCommand:
    # 是否仅主人
    isM: false
    # 是否允许群插件管理员
    isA: true
    # 是否允许群原生管理员
    isGA: false
    # 是否允许任何人
    isE: false

# 戳一戳设置
chuoyichuo:
  # 是否开启UC戳一戳
  isOpen: false
  # 被戳是否自动更新群名片
  isAutoSetCard: true
  # 开启被戳自动更新群名片后，群名片后缀内容，num会被替换为被戳次数
  groupCard: 今日已被戳num次~
  # 被戳回复文本+图片概率
  textimg: 0.8
  # 被戳回复被戳次数+文本+图片概率，此概率独立于整体概率，意为触发文本+图片回复时又有多少概率在文本前加上被戳次数，可选0-1
  chuoimg: 0.2
  # 被戳回复头像表情包概率
  face: 0.1
  # 被戳禁言对方概率，剩下的就是反击概率
  mute: 0.05
  # 禁言的时长，单位分，0为不禁言
  muteTime: 2

# 随机老婆设置
randomWife:
  # 是否开启UC随机老婆
  isOpen: true
  # 每日取老婆次数限制，包括主人
  wifeLimits: 1
  # 增加随机老婆权限
  add:
    # 是否仅主人可使用#上传随机老婆
    isM: false
    # 是否允许群插件管理员使用#上传随机老婆
    isA: true
    # 是否允许群原生管理员使用#上传随机老婆
    isGA: true
    # 是否允许任何人使用#上传随机老婆
    isE: false
  # 删除随机老婆权限
  del:
    # 是否仅主人可使用#删除随机老婆
    isM: false
    # 是否允许群插件管理员使用#删除随机老婆
    isA: true
    # 是否允许群原生管理员使用#删除随机老婆
    isGA: false
    # 是否允许任何人使用#删除随机老婆
    isE: false

# 随机群友设置
randomMember:
  # 是否开启UC随机群友
  isOpen: true
  # 是否自动艾特随机到的群友
  isAt: false
  # 触发指令，#你设置的值 就可以触发该插件，修改后直接生效，英语字母大小写都可以触发
  keyWords: 随机群友
  # 随机群友回复内容，info会被替换为群友信息：群友昵称（QQ）
  reply: 恭喜info成为天选之子！
  # 使用权限
  use:
    # 是否仅主人可使用
    isM: false
    # 是否允许群插件管理员使用
    isA: true
    # 是否允许群原生管理员使用
    isGA: true
    # 是否允许任何人使用
    isE: true

# B站直播推送设置
BlivePush:
  # 群聊推送全局开关
  isGroup: true
  # 私聊推送全局开关
  isPrivate: true
  # 推送检测间隔，单位分钟，不能小于1，不建议小于2，需要重启
  mins: 4
  # 订阅权限
  use:
    # 是否允许群聊使用，关闭仅主人可群聊使用
    isG: true
    # 是否允许私聊使用，关闭仅主人可私聊使用
    isP: false
    # 是否仅主人可使用
    isM: false
    # 是否允许群插件管理员使用，关闭仅主人或群原生管理员可使用
    isA: true
    # 是否允许群原生管理员使用，关闭仅主人或插件群管理员可使用
    isGA: true
    # 是否允许任何人使用，关闭仅主人或管理员可使用
    isE: false

# 放大图片设置
bigjpg:
  # 是否开启UC放大图片
  isOpen: true
  # 放大图片key
  apiKey:
  # 放大风格，art和photo，代表卡通和照片，卡通图片放大效果最佳
  style: art
  # 默认降噪级别，可选[0, 1, 2, 3, 4]，代表[无，低，中，高，最高]
  noise: 4
  # 默认放大倍数，可选[2倍，4倍，8倍，16倍]
  magnification: 2
  # 每人每天放大次数限制，0为不限制，主人不受限
  limits: 3
  # 放大的图片是否自动保存，保存位置 resources/bigjpg
  isSave: false
  # 4倍，关闭仅允许主人放大4倍
  x4: true
  # 8倍，关闭仅允许主人放大8倍
  x8: true
  # 16倍，关闭仅允许主人放大16倍
  x16: true
  # 订阅权限
  use:
    # 是否允许群聊使用，关闭仅主人可群聊使用
    isG: true
    # 是否允许私聊使用，关闭仅主人可私聊使用
    isP: false
    # 是否仅主人可使用
    isM: false
    # 是否允许群插件管理员使用，关闭仅主人或群原生管理员可使用
    isA: true
    # 是否允许群原生管理员使用，关闭仅主人或插件群管理员可使用
    isGA: true
    # 是否允许任何人使用，关闭仅主人或管理员可使用
    isE: false
