# 是否输出日志
log: true
# 插件主人是否和机器人主人合并，不影响管理设置
isDefaultMaster: true
# 插件优先级
priority: 251
# 选择服务
server: 2
# 是否仅主人可操作
onlyMaster: false
# 仅主人可操作时，对本拥有权限的管理的回复
onlyMasterReply: 当前仅允许主人操作
# 用户无权限回复
noPerReply: 无权限
# Bot无权限回复
noPowReply: 主淫，小的权限不足，无法执行该操作嘤嘤嘤~
# api连接失败回复
fetchErrReply: 服务连接失败，请稍后重试

# B站直播推送配置
BlivePush:
  # 群聊推送全局开关
  isGroup: true
  # 私聊推送全局开关
  isPrivate: true
  # 私聊订阅开关，关闭仅主人可私聊订阅
  isPrivateSubscribe: false
  # 是否允许群插件管理员订阅推送，关闭仅主人或群原生管理员可订阅
  isA: true
  # 是否允许群原生管理员订阅推送，关闭仅主人或插件群管理员可订阅
  isGA: true
  # 推送检测间隔，单位分钟，不能小于1，不建议小于2，需要重启
  mins: 4

# 刷屏检测配置
DetecteFloodScreen:
  # 刷屏检测开关
  isOpen: true
  # 刷屏触发数量
  judgeNum: 10
  # 是否警告，达到(刷屏数量-2)时提醒
  isWarn: true
  # 警告的回复内容
  warnText: 不要刷屏哦~
  # 惩罚方式：mute 或者 kick
  punishMode: mute
  # 触发惩罚的回复内容
  punishText: 天降正义！
  # 设置为禁言的禁言时长，单位分钟
  muteTime: 5
  # 设置为踢人时是否自动拉黑
  kickAndBlack: true

# 撤回、清屏配置
recall:
  # 允许获取的群聊天记录最大值，设置过大可能影响响应速度
  FILTER_MAX: 521
  # 清屏不指定数量时默认撤回数量
  clearNum: 10
  # 允许清屏数量的最大值
  RECALL_MAX: 100
  # 允许指定单人撤回的最大值
  PERSONAL_MAX: 20
  # 批量撤回群消息的间隔时间，单位秒
  intervalTime: 0.5
