# 是否开启UC群管功能，总开关
isOpen: false
# 开启UC群管后，UC群管是否只响应以UC为前缀的指令（防冲突用）
isPrefix: false
# 群管上下文操作的超时时间
overTime: 251

# 进群欢迎设置
welcome:
  # 是否开启UC群管进群欢迎
  isOpen: true
  # 进群欢迎是否展示新成员头像
  isAvatar: true
  # 进群欢迎是否艾特新成员
  isAt: false
  # 设置进群欢迎权限配置
  use:
    # 是否仅主人
    isM: false
    # 是否允许群插件管理员
    isA: true
    # 是否允许群原生管理员
    isGA: true
    # 是否允许任何人
    isE: false

# 退群通知设置
mourn:
  # 是否开启UC群管退群通知
  isOpen: true
  # 退群通知是否展示新成员头像
  isAvatar: true
  # 设置退群通知权限配置
  use:
    # 是否仅主人
    isM: false
    # 是否允许群插件管理员
    isA: true
    # 是否允许群原生管理员
    isGA: true
    # 是否允许任何人
    isE: false

# 撤回、清屏设置
recall:
  # 是否开启UC群管撤回
  isOpen: true
  # 允许递归获取的群聊天记录最大深度
  FILTER_MAX: 520
  # 清屏不指定数量时默认撤回数量
  defaultClear: 10
  # 允许清屏数量的最大值
  CLEAR_MAX: 100
  # 允许指定单人撤回的最大值
  RECALL_MAX: 20
  # 批量撤回群消息的间隔时间，单位秒，建议大于等于0.1
  intervalTime: 0.1
  # 撤回权限配置
  use:
    # 是否仅主人
    isM: false
    # 是否允许群插件管理员
    isA: true
    # 是否允许群原生管理员
    isGA: true
    # 是否允许任何人
    isE: false

# 禁言设置
mute:
  # 是否开启UC群管禁言
  isOpen: true
  # 允许禁言最大时长，单位秒（主人不限）
  MUTE_MAX: 86400
  # 禁言不指定时长时默认禁言时长，单位秒
  defaultMute: 60
  # 禁言时的回复，info会替换为 用户名（QQ），time会替换为禁言时长
  muteReply: 已经把info拖进小黑屋枪毙time啦！
  # 解禁时的回复，info会替换为 用户名（QQ）
  releaseReply: 成功解救info
  # 全体禁言回复
  allMuteReply: 全都不许说话了哦~
  # 全体解禁回复
  releaseAllMuteReply: 好耶~可以说话辽~
  # 全部解禁回复，num会被替换为解禁群员的数量
  releaseAllMutedReply: 归还了num名群员的清白之身！
  # 普通禁言权限配置
  use:
    # 是否仅主人
    isM: false
    # 是否允许群插件管理员
    isA: true
    # 是否允许群原生管理员
    isGA: true
  # 全体禁言权限配置
  muteAll:
    # 是否仅主人
    isM: false
    # 是否允许群插件管理员
    isA: true
    # 是否允许群原生管理员
    isGA: true

# 踢人设置
kick:
  # 是否开启UC群管踢人
  isOpen: true
  # 踢人后是否自动拉黑
  isAutoBlack: true
  # 踢人回复
  kickReply: 已经把这个坏惹踢掉了！
  # 普通踢人权限配置
  use:
    # 是否仅主人
    isM: false
    # 是否允许群插件管理员
    isA: true
    # 是否允许群原生管理员
    isGA: true

# 群员增加设置
Increase:
  # 是否开启UC群管群员增加处理（下列功能总开关）
  isOpen: true
  # 群员增加是否通知主人
  isNotice: false
  # 检测到是黑名单用户进群时是否自动踢出并撤回其所有消息
  isKickBlack: false
  # 自动踢出后的回复，info会替换为 用户名（QQ），BotName会替换为机器人名称
  kickBlackReply: 黑名单用户info，BotName已经把TA踢掉了！

# 群员减少设置
Decrease:
  # 是否开启UC群管群员减少处理（下列功能总开关）
  isOpen: true
  # 群员减少是否通知主人
  isNotice: false
  # 群员主动退群是否自动拉黑
  isAutoBlack: false

# 申请入群设置
RequestAdd:
  # 是否开启UC群管入群申请处理（下列功能总开关）
  isOpen: true
  # 是否自动同意入群申请（黑名单除外）
  isAutoApprove: false
  # 是否自动拒绝黑名单用户的入群申请
  isAutoRefuseBlack: true
  # 是否通知群（黑名单除外）
  isNoticeGroup: true
  # 入群申请是否通知主人
  isNoticeMaster: true
  # 同意拒绝入群申请权限
  use:
    # 是否仅主人
    isM: false
    # 是否允许群插件管理员
    isA: true
    # 是否允许群原生管理员
    isGA: true

# 刷屏检测设置
floodScreen:
  # 是否开启UC群管刷屏检测
  isOpen: false
  # 检测到黑名单用户发言是否自动踢出并撤回其消息
  isDetecteBlack: false
  # 刷屏检测时间范围，连续两条消息间隔时间小于此值则记为一次刷屏，单位秒
  timeRange: 10
  # 刷屏惩罚阈值，达到该次数则触发惩罚
  judgeNum: 10
  # 是否警告，达到(刷屏惩罚阈值-2)时警告
  isWarn: true
  # 刷屏警告的回复内容
  warnText: 不要刷屏哦~
  # 是否惩罚，达到刷屏惩罚阈值时惩罚
  isPunish: true
  # 惩罚方式：mute或kick
  punishMode: mute
  # 刷屏惩罚前的回复内容（关闭惩罚后仍会回复）
  punishText: 天天就知道刷屏❤️~杂鱼❤️~杂鱼❤️~
  # 设置为禁言时的禁言时长，单位分钟
  muteTime: 5
  # 设置为踢人时是否同时拉黑
  isAutoBlack: true

# 搜索群聊天记录
searchChatHistory:
  # 是否开启UC群管搜索群聊天记录
  isOpen: true
  # 默认搜索天数，仅当本地存在相应聊天记录时有效，否则只会查找当天或指定日期的聊天记录
  defaultDays: 7
  # 当本地聊天记录不存在时是否自动获取
  autoGet: true
  # 搜索权限
  use:
    # 是否仅主人
    isM: false
    # 是否允许群插件管理员
    isA: true
    # 是否允许群原生管理员
    isGA: true
    # 是否允许任何人
    isE: false
